package pl.discountapp.infrastructure.adapter.web;

public enum ErrorCode {
    COUPON_NOT_FOUND,
    COUPON_EXHAUSTED,
    COUNTRY_NOT_ALLOWED,
    COUPON_ALREADY_USED,
    COUPON_ALREADY_EXISTS,
    GEOLOCATION_UNAVAILABLE,
    RATE_LIMIT_EXCEEDED,
    VALIDATION_ERROR,
    CONCURRENT_MODIFICATION,
    INTERNAL_ERROR
}
